### ISSUE TITLE
How long should the process run?

### ISSUE THREAD

**Issue by Dutch-TS-Dev** [Adi-iitd/AI-Art#15]
Python noobie here. I am running Style_Transfer.py on a macbook with the following specs:
<img width="311" alt="Screenshot 2022-12-18 at 01 06 17" src="https://user-images.githubusercontent.com/19747468/208266021-3979781c-612d-4e8a-8ca5-18a81e7d581c.png">

Is it normal for the script to run more than 5 minutes or am I doing something wrong?  I shut the process off at some point because my laptop fans were going crazy.

**Comment by Adi-iitd** [comment]
One suggestion would be to constantly monitor the GPU usage and show the project on wandb/tensorboard. High chances are your code got stuck somewhere given the specs of the laptop.
