### ISSUE TITLE
Package doesn't work with URL images

### ISSUE THREAD

**Issue by RenaissanceEngineering** [Adi-iitd/AI-Art#8]
Tried running in Google Colab and on GPUs on AWS

Same error both times:

9 frames

/usr/local/lib/python3.7/dist-packages/imageio/core/request.py in _parse_uri(self, uri)
    271                 # Reading: check that the file exists (but is allowed a dir)
    272                 if not os.path.exists(fn):
--> 273                     raise FileNotFoundError("No such file: '%s'" % fn)
    274             else:
    275                 # Writing: check that the directory to write to does exist

FileNotFoundError: No such file: '/content/AI-Art/Dataset/StyleTransfer/Content.jpg'

**Comment by pgagarinov** [comment]
@PhilipMachineLearning I suggest you try https://github.com/pgagarinov/pytorch-hyperlight/blob/main/products/examples/nst/plain_simple_nst.ipynb 

https://github.com/pgagarinov/pytorch-hyperlight/blob/main/products/examples/nst/multi_style_nst.ipynb

Those two notebooks can download images directly from S3.

**Comment by RenaissanceEngineering** [comment]
Awesome thanks I'll try your package - will likely save me some time editing the source code!

Thanks @pgagarinov  !

**Comment by PhilipMachineLearning** [comment]
@pgagarinov Great that's working for your first example - but how do you scale the image up. Just using your example the image ends up being scaled to a smaller size?

Thanks in advance

**Comment by pgagarinov** [comment]
> Awesome thanks I'll try your package - will likely save me some time editing the source code!
> 
> Thanks @pgagarinov !

All you need to do is to change this constant that defines the target image size:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/4868370/111353424-59846f80-8696-11eb-9b5c-58efd7e45316.png">

Resizing is necessary because content and style images can have different sizes or/and proportions.
