### ISSUE TITLE
So how do I run this?

### ISSUE THREAD

**Issue by deama** [Adi-iitd/AI-Art#9]
So how would I install this AI-art on my machine and run it? The src just has the python source code, but no requirements.txt, or even what commands to run.

**Comment by ghost** [comment]
> So how would I install this AI-art on my machine and run it? The src just has the python source code, but no requirements.txt, or even what commands to run.

Hi, you can generate a requirements.txt file by running `pipreqs .` and it will generate a requirements.txt. If you run it at the root it will generate it for all the projects in src. If you only want to try one, just run it inside the dir for the one you'd like to try. I'd recommend using virtualenv or conda or some virtual environment to install the modules in so it doesn't conflict with other projects.

There's probably other stuff you need to do like install torch. The others have different instructions, and to figure it out I usually just try running the code then reading through it. You'll have to figure out most of it on your own.

For StyleTransfer, you need to place two files in `StyleTransfer/Dataset/Vision`. Content.jpg is the content you're transferring the style for, and Style.jpg is the style you're transferring.

That's all the help I'm going to be.
